[project]
name = "mygf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "casadi>=3.7.0",
    "matplotlib>=3.10.3",
    "pyqt5>=5.15.11",
    "scipy>=1.15.3",
]
